package com.dreamscale.htmflow.core.domain.tile;

public enum FlowObjectType {
    BRIDGE_ACTIVITY,
    BOX_ACTIVITY,
    BUBBLE,
    BUBBLE_CENTER,
    BUBBLE_ENTRANCE,
    BUBBLE_EXIT,
    BUBBLE_RING,
    BUBBLE_RING_LOCATION,
    BUBBLE_RING_LINK,
    RHYTHM_LAYER,
    MOVEMENT_CHANGE_CONTEXT,
    MOVEMENT_EXECUTE_THING,
    MOVEMENT_ACROSS_BRIDGE,
    MOVEMENT_TO_BOX,
    MOVEMENT_TO_LOCATION,
    MOVEMENT_POST_MESSAGE,
    TIMEBAND_LAYER,
    TIMEBAND,
    ROLLING_TIMEBAND,
    STORY_GRID,
    STORY_GRID_COLUMN,
    LIST_OF_FEATURES,

    //static types
    BOX,
    LOCATION,
    TRAVERSAL,
    CIRCLE_MESSAGE,
    CONTEXT,
    TASK_CONTEXT,
    INTENTION_CONTEXT,
    CONTEXT_BEGINNING_EVENT, CONTEXT_ENDING_EVENT, MOMENT_OF_CONTEXT, STORY_TILE, STORY_TILE_SUMMARY, BRIDGE
}
