package com.dreamscale.htmflow.core.domain.tile;

public enum FlowObjectType {
    BRIDGE_ACTIVITY,
    BOX_ACTIVITY,
    BUBBLE,
    BUBBLE_CENTER,
    BUBBLE_ENTRANCE,
    BUBBLE_EXIT,
    BUBBLE_RING,
    BUBBLE_RING_LOCATION,
    BUBBLE_RING_LINK,
    RHYTHM_LAYER,
    MOVEMENT_CHANGE_CONTEXT,
    MOVEMENT_EXECUTE_THING,
    MOVEMENT_MODIFY_LOCATION,
    MOVEMENT_ACROSS_BRIDGE,
    MOVEMENT_TO_BOX,
    MOVEMENT_TO_LOCATION,
    MOVEMENT_POST_MESSAGE,
    TIMEBAND_LAYER,
    TIMEBAND,
    ROLLING_TIMEBAND,
    STORY_GRID,
    STORY_GRID_ROW,
    STORY_GRID_AGGREGATE,
    STORY_GRID_AGGREGATE_ROW,
    STORY_GRID_COLUMN
}
