package com.dreamscale.gridtime.core.exception;

import org.dreamscale.exception.ErrorCodes;

import static com.dreamscale.gridtime.core.exception.ValidationErrorCodeGroups.VALIDATION;


public enum ValidationErrorCodes implements ErrorCodes {

    MISSING_OR_INVALID_ORGANIZATION(1, VALIDATION),
    MISSING_OR_INVALID_JIRA_PROJECT(2, VALIDATION),
    MISSING_OR_INVALID_JIRA_USER(3, VALIDATION),
    NO_ORG_MEMBERSHIP_FOR_ACCOUNT(4, VALIDATION),
    INVALID_PROJECT_REFERENCE(5, VALIDATION),
    INVALID_OR_EXPIRED_ACTIVATION_CODE(6, VALIDATION),
    INVALID_OR_EXPIRED_INVITATION_KEY(7, VALIDATION),
    MISSING_OR_INVALID_TEAM(8, VALIDATION),
    NO_INPUTS_PROVIDED(9, VALIDATION),
    INVALID_SEARCH_STRING(10, VALIDATION),
    INVALID_FINISH_STATUS(11, VALIDATION),

    FAILED_PUBLICKEY_GENERATION(12, VALIDATION),
    NO_ACCESS_TO_CIRCUIT(13, VALIDATION),
    ROOM_NOT_FOUND(14, VALIDATION),
    ROOM_ACCESS_DENIED(15, VALIDATION),
    UNABLE_TO_AUTHORIZE(16, VALIDATION),
    MISSING_OR_INVALID_CIRCUIT(17, VALIDATION),
    CIRCUIT_ALREADY_EXISTS(18, VALIDATION),
    MISSING_OR_INVALID_ROOM(19, VALIDATION),
    MISSING_OR_INVALID_WORD(20, VALIDATION),
    MISSING_OR_INVALID_BOOK(21, VALIDATION),
    WORD_NOT_FOUND_IN_BOOK(22, VALIDATION),
    INVALID_CONNECTION(23, VALIDATION),
    MEMBER_NOT_IN_TEAM(24, VALIDATION),
    MISSING_OR_INVALID_USERNAME(25, VALIDATION),
    MEMBER_NOT_MODERATOR_OF_TEAM(26, VALIDATION),
    MISSING_OR_INVALID_ACCOUNT_EMAIL(27, VALIDATION),
    MISSING_FIELD(28, VALIDATION),
    EMAIL_NOT_IN_DOMAIN(29, VALIDATION),
    NO_SUBSCRIPTION_FOUND(30, VALIDATION),
    MUST_BE_ORGANIZATION_OWNER(31, VALIDATION),
    MEMBER_NOT_FOUND(32, VALIDATION),
    NO_SUBSCRIPTION_SEAT_FOUND(33, VALIDATION),
    JIRA_CONFIGURATION_INVALID(34, VALIDATION),
    INVALID_USER_OR_PASSWORD(35, VALIDATION),
    TEAM_MUST_BE_OPEN_TO_JOIN(36, VALIDATION),
    UNABLE_TO_FIND_TERMINAL_ROUTE(37, VALIDATION),
    INVALID_TICKET_TYPE(38, VALIDATION),
    PROPERTY_CANT_BE_NULL(39, VALIDATION),
    PROJECT_MUST_BE_PRIVATE_TO_GRANT_ACCESS(40, VALIDATION),
    EXISTING_GRANT_NOT_FOUND(41, VALIDATION),
    PERMISSION_NOT_AUTHORIZED(42, VALIDATION),
    INTENTION_CANT_BE_EDITED(43, VALIDATION),
    FIELD_CANT_BE_BLANK(44, VALIDATION),
    INVALID_COMMAND_PARAMETERS(45, VALIDATION),
    MEMBER_NOT_JOINED_TO_CIRCUIT(46, VALIDATION),
    NO_DATA_AVAILABLE(47, VALIDATION),
    INVALID_GT_EXPRESSION(48, VALIDATION)
    ;


    private int subcode;
    private ValidationErrorCodeGroups errorCodeGroup;

    ValidationErrorCodes(int subcode, ValidationErrorCodeGroups errorCodeGroup) {
        this.subcode = subcode;
        this.errorCodeGroup = errorCodeGroup;
    }

    @Override
    public String makeErrorCode() {
        return this.errorCodeGroup.makeErrorCode(this.subcode);
    }
}
