package com.dreamscale.htmflow.core.domain.uri;

public enum FlowUriObjectType {
    BUBBLE_CENTER,
    BUBBLE_ENTRANCE,
    BUBBLE_EXIT,
    BUBBLE_RING,
    BUBBLE_RING_LOCATION,
    BUBBLE_RING_LINK,
    BUBBLE_BRIDGE_LINK,
    RHYTHM_LAYER,
    MOVEMENT_CHANGE_CONTEXT,
    MOVEMENT_EXECUTE_THING,
    MOVEMENT_MODIFY_LOCATION,
    MOVEMENT_ACROSS_BRIDGE,
    MOVEMENT_TO_BOX,
    MOVEMENT_TO_LOCATION,
    MOVEMENT_POST_MESSAGE,
    TIMEBAND_LAYER,
    TIMEBAND,
    BUBBLE
}
