package com.dreamscale.htmflow.core.feeds.executor.parts.observer;

import com.dreamscale.htmflow.api.circle.CircleMessageType;
import com.dreamscale.htmflow.core.domain.circle.CircleFeedMessageEntity;
import com.dreamscale.htmflow.core.feeds.common.Flowable;
import com.dreamscale.htmflow.core.feeds.executor.parts.fetch.flowable.FlowableCircleMessageEvent;
import com.dreamscale.htmflow.core.feeds.story.StoryTile;
import com.dreamscale.htmflow.core.feeds.executor.parts.source.Window;
import com.dreamscale.htmflow.core.feeds.story.feature.movement.Message;

import java.util.List;

/**
 * Translates the flame ratings on JournalEntries to TimeBands with a FeelsContext that always fits within
 * the frame and contributes to the push/pull signals generated by all the flames combined
 */
public class CircleMessageEventObserver implements FlowObserver {

    @Override
    public void see(Window window, StoryTile currentStoryTile) {

        List<Flowable> flowables = window.getFlowables();

        for (Flowable flowable : flowables) {
            if (flowable instanceof FlowableCircleMessageEvent) {
                CircleFeedMessageEntity circleMessage = ((CircleFeedMessageEntity) flowable.get());

                CircleMessageType circleMessageType = circleMessage.getMessageType();

                if (isScrapbookEvent(circleMessageType)) {
                    currentStoryTile.postCircleMessage(circleMessage.getPosition(), createIdeaDeails(circleMessage));
                }

            }

            currentStoryTile.finishAfterLoad();

        }

    }

    private Message createIdeaDeails(CircleFeedMessageEntity circleMessage) {
        Message message = new Message();

        message.setMessageFromTorchieId(circleMessage.getTorchieId());
        message.setMessageFromName(circleMessage.getFullName());

        message.setCircleId(circleMessage.getCircleId());
        message.setCircleName(circleMessage.getCircleName());

        message.setMessageId(circleMessage.getId());
        message.setMessageType(circleMessage.getMessageType());
        message.setMessage(circleMessage.getMessage());
        message.setFileName(circleMessage.getFileName());
        message.setFilePath(circleMessage.getFilePath());
        message.setSnippetSource(circleMessage.getSnippetSource());
        return message;
    }

    private boolean isScrapbookEvent(CircleMessageType circleMessageType) {
        return circleMessageType.equals(CircleMessageType.CHAT)
                || circleMessageType.equals(CircleMessageType.SCREENSHOT)
                || circleMessageType.equals(CircleMessageType.SNIPPET);
    }
}
