package com.dreamscale.htmflow.core.feeds.executor.parts.observer;

import com.dreamscale.htmflow.core.domain.journal.JournalEntryEntity;
import com.dreamscale.htmflow.core.feeds.executor.parts.fetch.flowable.FlowableJournalEntry;
import com.dreamscale.htmflow.core.feeds.story.TileBuilder;
import com.dreamscale.htmflow.core.feeds.story.feature.details.FeelsDetails;

import java.util.List;

/**
 * Translates the flame ratings on JournalEntries to TimeBands with a FeelsContext that always fits within
 * the frame and contributes to the push/pull signals generated by all the flames combined
 */
public class JournalFeelsObserver implements FlowObserver<FlowableJournalEntry> {

    @Override
    public void seeInto(List<FlowableJournalEntry> flowables, TileBuilder tileBuilder) {

        for (FlowableJournalEntry flowable : flowables) {
            JournalEntryEntity journalEntry = (flowable.get());

            Integer flameRating = journalEntry.getFlameRating();
            if (flameRating != null && flameRating != 0) {
                tileBuilder.startFeelsBand(journalEntry.getPosition(), new FeelsDetails(flameRating));
            } else {
                tileBuilder.clearFeelsBand(journalEntry.getPosition());
            }
        }

        tileBuilder.finishAfterLoad();

    }

}
