package com.dreamscale.gridtime.core.machine.executor.program.parts.observer;

import com.dreamscale.gridtime.core.domain.journal.JournalEntryEntity;
import com.dreamscale.gridtime.core.machine.executor.program.parts.feed.flowable.FlowableJournalEntry;
import com.dreamscale.gridtime.core.machine.executor.program.parts.source.Window;
import com.dreamscale.gridtime.core.machine.memory.tile.GridTile;

/**
 * Translates the flame ratings on JournalEntries to TimeBands with a FeelsContext that always fits within
 * the frame and contributes to the push/pull signals generated by all the flames combined
 */
public class JournalFeelsObserver implements FlowObserver<FlowableJournalEntry> {

    @Override
    public void observe(Window<FlowableJournalEntry> window, GridTile gridTile) {

        for (FlowableJournalEntry flowable : window.getFlowables()) {
            JournalEntryEntity journalEntry = (flowable.get());

            Integer flameRating = journalEntry.getFlameRating();
            if (flameRating != null && flameRating != 0) {
                gridTile.startFeelsBand(journalEntry.getPosition(), flameRating);
            } else {
                gridTile.clearFeelsBand(journalEntry.getPosition());
            }
        }

    }

}
