package com.dreamscale.htmflow.core.gridtime.executor.machine.parts.observer;

import com.dreamscale.htmflow.core.domain.journal.JournalEntryEntity;
import com.dreamscale.htmflow.core.gridtime.executor.machine.parts.fetch.flowable.FlowableJournalEntry;
import com.dreamscale.htmflow.core.gridtime.executor.memory.tile.GridTile;

import java.util.List;

/**
 * Translates the flame ratings on JournalEntries to TimeBands with a FeelsContext that always fits within
 * the frame and contributes to the push/pull signals generated by all the flames combined
 */
public class JournalFeelsObserver implements FlowObserver<FlowableJournalEntry> {

    @Override
    public void seeInto(List<FlowableJournalEntry> flowables, GridTile gridTile) {

        for (FlowableJournalEntry flowable : flowables) {
            JournalEntryEntity journalEntry = (flowable.get());

            Integer flameRating = journalEntry.getFlameRating();
            if (flameRating != null && flameRating != 0) {
                gridTile.startFeelsBand(journalEntry.getPosition(), flameRating);
            } else {
                gridTile.clearFeelsBand(journalEntry.getPosition());
            }
        }

    }

}
